name: pinapp_challenge
description: "Flutter challenge fo PinApp."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  app_client:
    path: packages/app_client
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  gap: ^3.0.1
  go_router: ^14.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
