name: pinapp_challenge
description: "Flutter challenge fo PinApp."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.6.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  core:
    path: ./packages/core

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
